Nicer error message with images missing from sweeps
Before:
  <traceback>
  AssertionError: Please report this error to dials-support@lists.sourceforge.net:
After:
  Sorry: Missing image 527 from imageset (0-540)