wx.Timer.Start expects an integer value for milliseconds.
This fixes:

TypeError: Timer.Start(): argument 1 has unexpected type 'float'

observed with wx 4.2.0